### Lista de inventory
GET http://localhost:3000/api/v1/inventory

### Agregar inventory
POST http://localhost:3000/api/v1/inventory
content-type: application/json

{
  "companyId": 1,
  "storeId": 1,
  "productId": 1,
  "quantity": 10
}

### Actualizar inventory || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/inventory/1
content-type: application/json

{
  "companyId": 1,
  "storeId": 1,
  "productId": 1,
  "quantity": 25
}

### Obtener inventory pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/api/v1/inventory/1
content-type: application/json

### Eliminar inventory pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/inventory/1
content-type: application/json