### Lista de orders
GET http://localhost:3000/api/v1/orders

### Agregar order
POST http://localhost:3000/api/v1/orders
content-type: application/json

{
  "number": "123231",
  "date": "2019-06-13",
  "supplierId": "1",
  "amount": "342.12",
  "companyId": "1"
}

### Actualizar order || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/orders/1
content-type: application/json

{
  "number": "8888",
  "date": "2015-06-13",
  "supplierId": "111111",
  "amount": "0.12",
  "companyId": "4345"
}

### Obtener order pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/api/v1/orders/1
content-type: application/json

### Eliminar order pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/orders/1
content-type: application/json