### Lista detalles de orden
GET http://localhost:3000/api/v1/order_details


### Agregar detalles de orden
POST http://localhost:3000/api/v1/order_details
content-type: application/json

{
  "orderId": "1",
  "storeId": "2",
  "productId": "3",
  "qtyRequested": 8,
  "qtyReceived": 3
}

### Actualizar detalles de orden || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/order_details/1
content-type: application/json

{
  "orderId": "1",
  "storeId": "2",
  "productId": "3",
  "qtyRequested": 10,
  "qtyReceived": 10
}

### Obtener detalles de orden pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/api/v1/order_details/1
content-type: application/json

### Eliminar detalles de orden pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/order_details/1
content-type: application/json