### Lista products
GET http://localhost:3000/api/v1/products

### Agregar products
POST http://localhost:3000/api/v1/products
content-type: application/json

{
  "code": "P-0001",
  "barcode": "333",
  "name": "Matias",
  "description": "asdas",
  "quantity": "4",
  "minimum" : "2",
  "categoryId": "1",
  "companyId": "1",
  "lastPurchaseDate": "2017-06-15",
  "lastPurchasePrice": "126",
  "lastSaleDate": "2019-05-01",
  "lastSalePrice": "216",
  "price": "134",
  "statusId": "1"
}

### Actualizar products
PUT http://localhost:3000/api/v1/products/1
content-type: application/json

{
  "id": "1",
  "code": "P-0023",
  "barcode": "546465466466",
  "name": "Vino",
  "description": "Vino Tomba",
  "quantity": "60",
  "minimum" : "10",
  "categoryId": "1",
  "companyId": "1",
  "lastPurchaseDate": "2017-06-15",
  "lastPurchasePrice": "126",
  "lastSaleDate": "2019-05-01",
  "lastSalePrice": "216",
  "price": "134",
  "statusId": "1"
}

### Obtener products pasando el id
GET http://localhost:3000/api/v1/products/1
content-type: application/json

### Eliminar product pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/products/1
content-type: application/json
