// TODO: CUIDADO ESTE REQUEST RESETEA LA BASE DE DATOS LOCAL
### Resetear la base de datos
POST http://localhost:3000/api/v1/reset-db
content-type: application/json


### Resetear sólo una tabla en la base de datos
POST http://localhost:3000/api/v1/reset-db/order_tracking
content-type: application/json



// FIXME: CUIDADO ESTE REQUEST RESETEA LA BASE DE DATOS EN QA
### Resetear la base de datos
POST https://vinoteca-api-qa.herokuapp.com/api/v1/reset-db
content-type: application/json


### Resetear sólo una tabla en la base de datos
POST https://vinoteca-api-qa.herokuapp.com/api/v1/reset-db/inventory_variation
content-type: application/json



// FIXME: CUIDADO ESTE REQUEST RESETEA LA BASE DE DATOS EN PRODUCCION
### Resetear la base de datos
POST https://vinoteca-api.herokuapp.com/api/v1/reset-db
content-type: application/json

### Resetear sólo una tabla en la base de datos
POST https://vinoteca-api.herokuapp.com/api/v1/reset-db/inventory_variation
content-type: application/json
