### Lista de sales
GET http://localhost:3000/api/v1/sales

### Agregar order
POST http://localhost:3000/api/v1/sales
content-type: application/json

{
  "date": "2020-09-16",
  "number": "00025"
}

### Actualizar order || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/sales/1

{
  "date": "2015-06-13"
}

### Obtener order pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/api/v1/sales/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29tcGFueUlkIjoxLCJuYW1lIjoiT21hciIsInByb2ZpbGVJZCI6MSwiaWF0IjoxNTk0MzIwMTg4LCJleHAiOjE1OTQ0OTI5ODgsImlzcyI6Imh0dHA6Ly92aW5vdGVjYS1hcGkuaGVyb2t1YXBwLmNvbS8ifQ.BIrP8HuD6cRbdyMpDNgKcrqcxLbp2zDcMAR6tNuOn0o


### Eliminar order pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/sales/1


### Enviar orden de compra al proveedor
POST http://localhost:3000/api/v1/send-order/1
content-type: application/json
