### Agregar detalles de orden
POST http://localhost:3000/api/v1/sale_details
content-type: application/json

{
  "saleId": "2",
  "productId": "1",
  "quantity": 3
}

### Actualizar detalles de orden || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/sale_details/3
content-type: application/json

{
  "quantity": 2
}

### Get by id
GET http://localhost:3000/api/v1/sale_details/5
content-type: application/json

### Eliminar detalles de orden pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/sale_details/5
content-type: application/json