### Lista stock variation reasons
GET http://localhost:3000/api/v1/stock_variation_reasons


### Agregar stock variation reasons
POST http://localhost:3000/api/v1/stock_variation_reasons
content-type: application/json

{
 "code" : "123",
 "name" : "Nombre",
 "companyId" : "1"
}

### Actualizar stock variation reasons || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/api/v1/stock_variation_reasons/1
content-type: application/json

{
  "code" : "123",
  "name" : "Nombre nuevo",
  "companyId" : "2"
}

### Obtener stock variation reasons pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/api/v1/stock_variation_reasons/1
content-type: application/json

### Eliminar stock variations pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/api/v1/stock_variation_reasons/1
content-type: application/json
